#!/bin/bash
set -ex
if [ ! -f /usr/local/bin/rememberwindows ]; then
    echo "Error: Binary not found" >&2
    exit 1
fi
/bin/launchctl stop /Library/LaunchDaemons/com.github.iffy.rememberwindows.plist || true
/bin/launchctl disable /Library/LaunchDaemons/com.github.iffy.rememberwindows.plist || true
/bin/launchctl load -w /Library/LaunchDaemons/com.github.iffy.rememberwindows.plist
exit 0